contracts/facets/membership/VerificationFacet.sol, contracts/facets/token/ERC20/claiming/one-time/ERC20OneTimeRewardFacet.sol, contracts/facets/token/ERC20/claiming/one-time/ERC20OneTimeVerificationRewardFacet.sol, contracts/facets/token/ERC20/claiming/time/ERC20TimeClaimableFacet.sol, contracts/libraries/storage/LibERC20OneTimeVerificationRewardStorage.sol, deployments/deploy_DiamondGovernance.ts, deployments/deploy_Libraries.ts, test/Test_ERC20TimeClaimableFacet.ts, test/Test_PartialVoting.ts, tsconfig.json, utils/timeUnits.ts, utils/verificationHelper.ts
- Added one time verification reward facet
- Fixed verification facet tier always returning 3
=> feat: One time verification reward facet, fix: verification facet

contracts/facets/governance/proposal/PartialBurnVotingProposalFacet.sol, contracts/facets/token/ERC20/claiming/refund/ERC20PartialBurnVotingProposalRefundFacet.sol, contracts/facets/token/ERC20/claiming/refund/ERC20PartialBurnVotingRefundFacet.sol, contracts/libraries/storage/LibPartialBurnVotingProposalStorage.sol, deployments/deploy_DiamondGovernance.ts
- Added facet for claiming back proposal creation cost after the proposal has passed.
=> feat: Proposal cost is refundable when proposal passed

contracts/facets/membership/VerificationFacet.sol, contracts/facets/securesecoMonetization/SearchSECOMonetizationFacet.sol, contracts/libraries/storage/LibSearchSECOMonetizationStorage.sol, contracts/libraries/storage/LibVerificationStorage.sol, contracts/upgradeInitializers/DiamondInit.sol, deployments/deploy_DiamondGovernance.ts, deployments/deploy_Libraries.ts
- Added SearchSECOMonetizationFacet. This is for the integration with SearchSECO (and monetization of queries).
=> feat: added searchseco monetization facet

contracts/facets/securesecoMonetization/SearchSECOMonetizationFacet.sol, deployments/deploy.ts
(Critical fixes) Changed ERC20 to IERC20 and network to network.name.
Ran npm test
=> fix: erc20 to ierc20 + network to network.name

contracts/facets/github-pr/GithubPullRequestFacet.sol, contracts/facets/mocks/GithubPullRequestMockFacet.sol, sdk/src/sugar/actions.ts, test/Test_GithubPullRequest.ts, test/Test_SDK.ts
Added test for github pull request proposal creation (using actions). Also changed some names because they did not meet naming conventions
Ran npm test (with it.only for the relevant test)
=> test + fix: added test for gh pr proposal creation + naming changes

contracts/facets/searchseco-monetization/SearchSECOMonetizationFacet.sol, contracts/facets/searchseco-rewarding/SearchSECORewardingFacet.sol, contracts/facets/searchseco-rewarding/SignatureHelper.sol, contracts/libraries/storage/LibSearchSECORewardingStorage.sol, contracts/upgrade-initializers/DiamondInit.sol, contracts/upgrade-initializers/single-contract-init/DISearchSECORewarding.sol, contracts/upgrade-initializers/single-contract-init/DISearchSecoMonetization.sol, deployments/deploy_DGSelection.ts, deployments/deploy_DiamondGovernance.ts, deployments/deploy_Libraries.ts, test/Test_SearchSECORewarding.ts
Implemented SearchSECORewardingFacet, which will reward users upon providing a proof of having mined hashes.
Also renamed some folder to be consistent with naming conventions.
npx hardhat test
=> feat+fix: SearchSECORewardingFacet

README.md
Added paragraph about sdk to readme, fixed some typos
=> docs: add sdk to readme

README.md
- Added more backticks and links to improve reader experience (thanks @ThijnK )
- Reformulated unclear sentences
=> docs: Requested changes

contracts/facets/mocks/SearchSECORewardingMockFacet.sol, contracts/facets/searchseco-rewarding/SearchSECORewardingFacet.sol, contracts/libraries/storage/LibSearchSECORewardingStorage.sol, test/Test_SearchSECORewarding.ts
Adds hash reward variable & tests to `SearchSECORewardingFacet`
=> feat + test: add get/set hash reward & tests

sdk/src/abi/verificationContractAbi.ts, sdk/src/sugar/data.ts, sdk/src/verification.ts, test/Test_SDK.ts
Changed some verification sugar functions to return the contract transaction.
Added reverifyThreshold getter sugar in verification.ts.
Removed specific action types from data.ts.
Test was written for reverifyThreshold.
=> Sdk fixes: add reverifyThreshold + removed action types

contracts/other/verification/SignVerification.sol, contracts/utils/GenericSignatureHelper.sol, test/Test_Verification.ts
Update SignVerification and GenericSignatureHelper to latest version. This includes a fix prevent people from verifying.
The tests can be found on their repository: [https://github.com/SecureSECODAO/SecureSECOVerification/tree/dev/block/test](https://github.com/SecureSECODAO/SecureSECOVerification/tree/dev/block/test)
=> chore: Update SignVerification to latest version

sdk/package-lock.json, sdk/package.json, sdk/src/sugar.ts, sdk/src/sugar/proposal-cache.ts, test/Test_PartialVoting.ts, test/Test_PartialVotingProposal.ts, test/Test_ProposalSDKSugar.ts
Added tests to verify sorting of proposals is working correctly.
=> test: sorting proposals

deployments/deploy_DiamondGovernance.ts, scripts/Deploy.ts
Added the proposal cost and respective refund facet to the deploy of the DAO.
=> chore: add proposal cost to deploy

scripts/Deploy.ts
=> fix: add deploy of mining reward pool facet to deploy.ts

README.md, scripts/Deploy.ts, scripts/GenerateDiamondCutProposal.ts
Added a script to generate a proposal to cut a diamond.  This will make it easier for facet devs to propose a cut with their new facet. It has not been added as npm command on purpose, as this command should be modified in the file before running. 
The command has been used to generate a proposal with a diamond cut: https://dao.secureseco.org/governance/proposals/23
=> feat: diamond cut proposal generator

contracts/facets/multiplier/IRewardMultiplierFacet.sol, contracts/facets/multiplier/RewardMultiplierFacet.sol
Note that this is for the "inflation" variable specifically. 
npm test
=> feat: get/set for inflation timestamp

contracts/facets/governance/structure/membership/IMembershipExtended.sol, contracts/facets/governance/structure/membership/ITieredMembershipStructure.sol, contracts/facets/membership/IVerificationFacet.sol, contracts/facets/membership/VerificationFacet.sol, contracts/facets/token/ERC20/claiming/one-time/ERC20OneTimeVerificationRewardFacet.sol, contracts/facets/token/ERC20/claiming/time/ERC20TieredTimeClaimableFacet.sol, contracts/facets/token/ERC20/claiming/time/ERC20TimeClaimableFacet.sol, contracts/libraries/storage/LibVerificationStorage.sol, contracts/other/verification/SignVerification.sol, deployments/deploy_DiamondGovernance.ts, scripts/Deploy.ts, sdk/src/verification.ts, test/Test_ERC20TimeClaimable.ts, test/Test_Verification.ts, test/Test_VerificationRewardPool.ts
Make diamond governance owner of the verification contract.
Also changed every instance of block timestamp related to verification to block number.
=> fix: add transfer ownership to verification

contracts/other/verification/SignVerification.sol, deployments/deploy_DiamondGovernance.ts
Split owner and signer in the signverification contract
=> fix: split owner and signer

sdk/package.json, sdk/src/sugar/proposal.ts
Proposal status could be "pending" incorrectly, as currentTime in milisecond was compared to startDate in seconds.
=> fix: proposal pending

sdk/package-lock.json, sdk/package.json, sdk/src/sugar/proposal.ts
Fix for incorrect proposal status in the SDK.
=> fix: proposal status

sdk/package-lock.json, sdk/package.json
=> fix: sdk version increase
